### ISSUE TITLE
Save List Data

### ISSUE THREAD

**Issue by EKKOING** [BLT-App/BLT-Hi-Fi#24]
Change the way we access list data to access the data every time we need it instead of using a global variable. This data should be persistent when relaunching the app.

**Comment by jchen** [comment]
Initial bug (haven't tested more): 
Adding an item does not add the correct item to the top of the list. I think this is caused by problems due to sorting by the due date that causes new problems to show up later in the list, although the to-do list expects new items to be added in index 0.
